Throw error when browers option is not an array
I forgot that the `browsers` option must be an array. This commit 
catches this case and throws a more descriptive error instead of 
something a long the lines of `TypeError: undefined is not a function`